language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

env: FC=gfortran

addons:
  apt:
#    sources: ubuntu-toolchain-r-test
    packages:
    - gfortran


matrix:
  include:
  - os: linux
    before_install:
    - curl -Ls https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip -o ninja-linux.zip
    - sudo unzip ninja-linux.zip -d /usr/local/bin/
    - python -m pip install -e meson
#  - os: osx
#    before_install:
#    - brew update > /dev/null
#    - brew install gcc > /dev/null

install: pip install -e .

script: pytest -r a -v
