jobs:

- job: Ubuntu
  pool:
    vmImage: ubuntu-latest

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
  - script: sudo apt install -yq --no-install-recommends gfortran
    displayName: 'Install Prereqs'
  - script: |
      python -m pip install meson
      curl -Ls https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip -o ninja-linux.zip
      sudo unzip ninja-linux.zip -d /usr/local/bin/
    displayName: 'Setup Meson'
  - script: pip install -e .[tests]
    displayName: 'Build Python'
  - script: pytest -r a -v
    displayName: 'PyTest'

- job: MacOS
  pool:
    vmImage: macOS-10.14

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
  - script: brew install gcc meson
    displayName: 'Install Prereqs'
  - script: pip install -e .[tests]
    displayName: 'Build Python'
  - script: pytest -r a -v
    displayName: 'PyTest'

- job: WindowsMinGW
  pool:
    vmImage: windows-2019

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
  - script: |
      cinst -y mingw ninja
      pip install meson
    displayName: 'Install Prereqs'
  - script: pip install -e .[tests]
    displayName: 'Build Python'
  - script: pytest -r a -v
    displayName: 'PyTest'