jobs:

- job: Ubuntu
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
  - script: |
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      sudo apt update -q
      sudo apt install -yq --no-install-recommends gfortran-6 octave
    displayName: 'Install Prereqs'
  - script: |
      python -m pip install meson
      curl -Ls https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip -o ninja-linux.zip
      sudo unzip ninja-linux.zip -d /usr/local/bin/
    displayName: 'Setup Meson'
  - script: pip install -e .[tests]
    env:
      FC: gfortran-6
    displayName: 'Build Python'
  - script: pytest -r a -v
    displayName: 'PyTest'

- job: MacOS
  pool:
    vmImage: macOS-10.14

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
  - script: brew install gcc meson
    displayName: 'Install Prereqs'
  - script: pip install -e .[tests]
    displayName: 'Build Python'
  - script: pytest -r a -v
    displayName: 'PyTest'
