image:
- Visual Studio 2017
- Ubuntu1804

stack: python 3

environment:
  MINGW_DIR: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin
  PY_DIR: C:\Python37-x64

clone_depth: 25

build: off

init:
- cmd: set PATH=%MINGW_DIR%;%PATH%
- cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%
# Ninja
- sh: curl -Ls https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip -o /tmp/ninja-linux.zip
- sh: sudo unzip /tmp/ninja-linux.zip -d /usr/local/bin/
- cmd: cinst -y ninja

install:
- python -m pip install meson
- meson build

test_script:
- meson test -C build
