name: ci_linux

on: [push, pull_request]

jobs:

  # cmake was too old

  meson:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: python -m pip install meson
    - run: sudo apt install -yq --no-install-recommends ninja-build gfortran
    - run: meson setup build
      env:
        FC: gfortran
    - run: meson test -C build -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Meson_Testlog
        path: build/meson-logs/testlog.txt
    - run: pip install -e .[tests,lint]
    - run: flake8
    - run: mypy .
    - run: pytest -r a -v